In [2]:
import numpy as np
import pandas as pd

1. Utwórz DataFrame zawierający dane 10 osób, wzrost w centymetrach oraz masę ciała w kilogramach. Następnie na podstawie tych danych wygeneruj kolumnę zawierającą BMI każdej osoby.

In [3]:
names = ["Ania", "Paweł", "Joachim", "Hanna", "Elżbieta", "Benjamin", "Ernest", "Paulina", "Władysław", "Żaneta"]
height = np.random.randint(150, 200, size=10)
height.astype(float)
weight = np.random.randint(60, 120, size=10)

dane=list(zip(names, height, weight))

df1 = pd.DataFrame(dane, columns=['names', 'height', 'weight'])
df1
df1["BMI"] = round(df1["weight"]/pow(df1["height"]/100, 2), 2)
df1

       names  height  weight    BMI
0       Ania     181     108  32.97
1      Paweł     172     113  38.20
2    Joachim     185      61  17.82
3      Hanna     187     111  31.74
4   Elżbieta     186     100  28.91
5   Benjamin     154      61  25.72
6     Ernest     166      77  27.94
7    Paulina     183      75  22.40
8  Władysław     196     114  29.68
9     Żaneta     196      61  15.88

2. Utwórz własny DataFrame zawierający wybrane przez siebie dane. Zapisz go do pliku JSON, a następnie wczytaj ten plik do nowego obiektu DataFrame. Sprawdź, czy oba obiekty zawierają te same dane.

In [10]:
df2 = pd.DataFrame({
    'produkt': ['jabłko', 'banan', 'gruszka'],
    'cena': [2.50, 3.20, 4.10],
    'liczba_sztuk': [10, 7, 5],
    'kategoria': ['owoce', 'owoce', 'owoce']
})
df2

df2.to_json('df2.json', orient='records', lines=True)

df2_j = pd.read_json('df2.json', orient='records', lines=True)
df2_j

df2 != df2_j

print(df2.equals(df2_j))

True

3. Wykorzystaj DataFrame stworzony w punkcie 1. Dodaj kolumnę z wiekiem i wypełnij ją danymi. Następnie znajdź osoby starsze niż średnia wieku wszystkich osób, których BMI jest jednocześnie większe niż 25. Wyświetl imiona, wiek oraz BMI tych osób.

In [ ]:
df1["age"] = np.random.randint(18, 65, size=10)
df1

wynik = df1[
    (df1["age"] > df1["age"].mean()) &
    (df1["BMI"] > 25)
]

wynik[["names", "age", "BMI"]]

      names  age    BMI
1     Paweł   64  38.20
3     Hanna   51  31.74
4  Elżbieta   42  28.91
6    Ernest   64  27.94